import React, { FC, ReactNode, useRef, useState } from "react";
import { createCache, extractStyle, StyleProvider, StyleProviderProps } from "@ant-design/cssinjs";
import { useServerInsertedHTML } from "next/navigation";

// *** https://github.com/ant-design/nextjs-registry/blob/main/src/AntdRegistry.tsx

type AntdRegistryProps = Omit<StyleProviderProps, "cache">;

const AntdRegistry: FC<AntdRegistryProps> = (props) => {
	const [cache] = useState(() => createCache());
	const inserted = useRef(false);
	// useServerInsertedHTML
	useServerInsertedHTML(() => {
		const styleText = extractStyle(cache, { plain: true });
		// check
		if (inserted.current) {
			return null;
		}
		inserted.current = true;
		// return JSX
		return (
			<style
				id="antd-cssinjs"
				// data-rc-order="prepend" // *** to make sure this style is inserted before Ant Design's style generated by client
				data-rc-priority="-1000"
				dangerouslySetInnerHTML={{ __html: styleText }}
			/>
		);
	});
	// return
	return <StyleProvider {...props} cache={cache} />;
};

export default AntdRegistry;
