import "@/assets/styles/global.css";
import { Inter } from "next/font/google";

import { IParams } from "@/utils/langs";
import GlobalStates from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export async function generateStaticParams() {
	return [{ locale: "fa" }, { locale: "en" }];
}

type IRootProps = {
	children: React.ReactNode;
};

export default function RootLayout({ children, params: { locale } }: IParams & IRootProps) {
	return (
		<html lang={locale}>
			<body>
				<GlobalStates>{children}</GlobalStates>
			</body>
		</html>
	);
}
