import "@/assets/styles/global.css";
import { Inter } from "next/font/google";

import GlobalStates from "@/context";
import { locales } from "@/utils/langs";
import { PropsWithParams } from "@/utils/types/configs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export async function generateStaticParams() {
	return locales.map((locale) => ({ locale }));
}

export default function RootLayout({ children, params: { locale } }: PropsWithParams) {
	return (
		<html lang={locale}>
			<body>
				<GlobalStates locale={locale}>{children}</GlobalStates>
			</body>
		</html>
	);
}
