import "@/assets/styles/global.css";
import { Inter } from "next/font/google";

import { locales, IParams } from "@/utils/langs";
import GlobalStates from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export async function generateStaticParams() {
	return locales.map((locale) => ({ locale }));
}

type IRootProps = {
	children: React.ReactNode;
};

export default function RootLayout({ children, params: { locale } }: IRootProps & IParams) {
	return (
		<html lang={locale}>
			<body>
				<GlobalStates locale={locale}>{children}</GlobalStates>
			</body>
		</html>
	);
}
